### ISSUE TITLE
Support für Variant-Sprachen fehlt

### ISSUE THREAD

**Issue by LProemer** [porscheinformatik/weblate-spring#17]
Es gibt zwei issues im WeblateMessageSource:

**In loadLocales:** 
Weblate liefert den locale code als "de_DE@DEV"
Für Locale.forLanguageTag() müsste der Code jedoch in "de-DE-x-lvariant-DEV" umgeschrieben werden. 
Aktuell jedoch wird er nur auf de-DE@DEV umgeschrieben. 

**in loadTranslations(Locale language)**
Hier wird in der uri Locale.toString() verwendet, die jedoch die Locale im Format "de_DE_DEV" ausgibt.
Weblate bräuchte aber das format: "de_DE@DEV"

**in loadTranslations(Locale language, boolean forceReload)**
Variant Sprache sollte hier im besten fall separat geladen werden.

LG Lukas

**Comment by LProemer** [comment]
https://github.com/porscheinformatik/weblate-spring/pull/18

**Comment by derkoe** [comment]
Fixed by #20
